fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    ntp:
      repo: "https://github.com/puppetlabs/puppetlabs-ntp.git"
      ref: "4.2.0"
    profile_base: "https://github.com/relybv/dirict-profile_base.git"
    rspec_monitor: "git://github.com/pgomersbach/test-rspec_monitor.git"
    concat: "https://github.com/puppetlabs/puppetlabs-concat.git"
    haproxy: "https://github.com/puppetlabs/puppetlabs-haproxy.git"
    profile_haproxy: "https://github.com/relybv/dirict-profile_haproxy.git"
    rsyslog: "https://github.com/saz/puppet-rsyslog.git"
    motd: "https://github.com/puppetlabs/puppetlabs-motd.git"
    gai: "https://github.com/smoeding/puppet-gai.git"
    apt: "https://github.com/puppetlabs/puppetlabs-apt.git"


  symlinks:
    role_lb: "#{source_dir}"
